spring.application.name=LibraryManagementSystem
server.port=10000

# ======================
# DATABASE CONFIG (DIRECT CONNECTION FIXED)
# ======================
spring.datasource.url=jdbc:postgresql://ep-curly-voice-aigw4w8m.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_LXtw0FpOaJf1
spring.datasource.driver-class-name=org.postgresql.Driver

# ======================
# JPA / HIBERNATE (TEMPORARY DATABASE RESET)
# ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ======================
# FILE UPLOAD (IMPORTANT)
# ======================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ======================
# LOGGING
# ======================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
