spring.application.name=LibraryManagementSystem
server.port=8081

# ======================
# DATABASE CONFIG
# ======================
spring.datasource.url=jdbc:postgresql://ep-curly-voice-aigw4w8m-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner.ep-curly-voice-aigw4w8m
spring.datasource.password=npg_nSmKs801vrbp
spring.datasource.driver-class-name=org.postgresql.Driver

# ======================
# JPA / HIBERNATE (TEMPORARY DATABASE RESET)
# ======================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ======================
# FILE UPLOAD (IMPORTANT)
# ======================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ======================
# LOGGING
# ======================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
